server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn_spring-boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Xy001211@xy

mybatis:
  configuration:
    map-underscore-to-camel-case: true